sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t twizzx/frontend-test -f Dockerfile.dev .

script:
  - docker run -e CI=true twizzx/frontend-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-056358467392"
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
