sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t twizzx/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true twizzx/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "reactv3"
  env: "Reactv3-env"
  bucket_name: "elasticbeanstalk-eu-north-1-056358467392"
  bucket_path: "reactv3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
