sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t twizzx/frontend-test -f Dockerfile.dev .

script:
  - docker run -e CI=true twizzx/frontend-test npm run test